### PR TITLE
Update paper based on review comments

### PR DESCRIPTION
**Pull request by asmeurer**
Ref: https://github.com/scipy-conference/scipy_proceedings/pull/822

### CODE REVIEW

**Comment by asmeurer** [comment]
I think I've addressed everything. @kgryte if you have a chance to look this over that would be great.

Also it looks like these changes pushed us over the 8 page limit again, so we'll need to fix that somehow.

**Comment by asmeurer** [comment]
Actually just adding John as an author pushed us over the 8 page limit, but this has made it worse.

**Comment by kgryte** [comment]
@asmeurer I'll try and take a look on Friday and shuffle around content accordingly. I am fairly confident I can get us to under the limit with minimal tweaks.

**Comment by asmeurer** [comment]
I still think we can remove the "optional extensions" section :) (actually even removing that section is not enough with this current draft)

> @asmeurer I'll try and take a look on Friday and shuffle around content accordingly. I am fairly confident I can get us to under the limit with minimal tweaks.

Shall I go ahead and submit what is here to the proceedings PR, or should we wait?

**Comment by kgryte** [comment]
I'd wait, as we have time.

**Review by kgryte — APPROVED** [review]

**Pull request merged**
