### PR TITLE
Add leofang as author

### PR DESCRIPTION
**Pull request by leofang**

### CODE REVIEW

**Comment by leofang** [comment]
Another question: Do we plan to acknowledge fundings? Is this common in SciPy papers?

**Comment by kgryte** [comment]
Re: funding. Good question. @rgommers you have thoughts here? IIRC, if a paper originates from private (non-grant) based funding (e.g., engineers from a company publish a paper on company time), the funding is not typically explicitly mentioned.

**Comment by rgommers** [comment]
No need for funding mentions I'd say, we captured that in blog posts and talks already, and there are no requirements to include it (as there would be for grants). Grant-funded scientific work is also typically fully-funded, while we have a mix of companies putting in hard dollars, and folks who contributed either as part of their day job or outside of that. So it's nontrivial to give accurate credit in 1-2 sentences.

**Comment by leofang** [comment]
Thanks, Ralf/Athan. Updated my PR. 

btw, I don't know the criteria for `:equal-contributor:` and I'll leave it up to you to decide. I noticed Stephan didn't add it (#5).

**Comment by asmeurer** [comment]
Just want to confirm this is OK to merge now. 

I guess we'll need to figure out how we want to order the authors and how we want to do equal contributors. I guess there's "equal contributor" and also "corresponding". See for example, https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2018/papers/project_jupyter/paper.rst.

**Comment by kgryte** [comment]
@asmeurer Go ahead and merge and we can sort out order, etc, later.

**Comment by leofang** [comment]
Yeah, I have no opinion in sorting or equal-contribution criterion 🙂

**Review by kgryte — APPROVED** [review]

**Pull request merged**
